### ISSUE TITLE
Error on PDF creation

### ISSUE THREAD

**Issue by dasistwas** [alyf-de/eu_einvoice#10]
After installing the app on version-15 I get this error, when I go to Sales Invoice and try to create a PDF invoice:

```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1725, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/eu_einvoice/eu_einvoice/european_e_invoice/custom/sales_invoice.py", line 623, in download_pdf
    frappe.local.response.filecontent = attach_xml_to_pdf(name, frappe.local.response.filecontent)
  File "apps/eu_einvoice/eu_einvoice/european_e_invoice/custom/sales_invoice.py", line 639, in attach_xml_to_pdf
    xml_bytes = get_einvoice(invoice_id)
  File "apps/eu_einvoice/eu_einvoice/european_e_invoice/custom/sales_invoice.py", line 71, in get_einvoice
    generator.create_einvoice()
  File "apps/eu_einvoice/eu_einvoice/european_e_invoice/custom/sales_invoice.py", line 112, in create_einvoice
    if self.invoice.buyer_reference:
AttributeError: 'SalesInvoice' object has no attribute 'buyer_reference'
```

**Comment by 0xD0M1M0** [comment]
Which version of Frappe and ERPNext is installed?
Only starting v15.45.0 the fields are introduced to ERPNext.

**Comment by dasistwas** [comment]
Hi @0xD0M1M0,
thank you for the swift reply. These are the apps and versions installed:
```
erpnext 15.45.0
erpnextswiss 1.23.1
frappe 15.49.1
hrms 15.35.3
payments 0.0.1
```

**Comment by barredterra** [comment]
This is most likely due to your failed installation (#9)
